name: BlockCityTycoonEconomy
version: '${project.version}'
main: me.darkmun.blockcitytycooneconomy.BlockCityTycoonEconomy
authors: [ Darkmun ]
depend: [ Vault ]
commands:
  business:
    description: Главная команда плагина.
  increaseincome:
    description: Увеличивает доход указанному игроку на заданное количество процентов.
  testt:
    description: asd